### PR TITLE
Fix the duplicate of the result list

### LINKED ISSUE #190: When run duf with a path, result is not expected (linux_armv7 on rpi4)
## Files in the path
pi@pi4:~ $ exa /mnt/240G/pt --tree
/mnt/240G/pt
├── Collins COBUILD (CN).mdd
├── Collins COBUILD (CN).mdx
├── Collins COBUILD (CN).png
└── text
   ├── test1
   └── test2

## E.g. 1
pi@pi4:~ $ duf /mnt/240G/pt
╭───────────────────────────────────────────────────────────────────╮
│ 1 local device                                                    │
├────────────┬────────┬───────┬────────┬────────┬──────┬────────────┤
│ MOUNTED ON │   SIZE │  USED │  AVAIL │  USE%  │ TYPE │ FILESYSTEM │
├────────────┼────────┼───────┼────────┼────────┼──────┼────────────┤
│ /mnt/240G  │ 219.1G │ 73.3G │ 134.6G │  33.5% │ ext4 │ /dev/sdb1  │
╰────────────┴────────┴───────┴────────┴────────┴──────┴────────────╯

## E.g. 2
pi@pi4:~ $ duf /mnt/240G/pt/*
╭───────────────────────────────────────────────────────────────────╮
│ 4 local devices                                                   │
├────────────┬────────┬───────┬────────┬────────┬──────┬────────────┤
│ MOUNTED ON │   SIZE │  USED │  AVAIL │  USE%  │ TYPE │ FILESYSTEM │
├────────────┼────────┼───────┼────────┼────────┼──────┼────────────┤
│ /mnt/240G  │ 219.1G │ 73.3G │ 134.6G │  33.5% │ ext4 │ /dev/sdb1  │
│ /mnt/240G  │ 219.1G │ 73.3G │ 134.6G │  33.5% │ ext4 │ /dev/sdb1  │
│ /mnt/240G  │ 219.1G │ 73.3G │ 134.6G │  33.5% │ ext4 │ /dev/sdb1  │
│ /mnt/240G  │ 219.1G │ 73.3G │ 134.6G │  33.5% │ ext4 │ /dev/sdb1  │
╰────────────┴────────┴───────┴────────┴────────┴──────┴────────────╯
Show 4 lines. I think it's because there are 3 files and 1 directory

## Result of 'du'
pi@pi4:~ $ du /mnt/240G/pt/
4       /mnt/240G/pt/text
13616   /mnt/240G/pt/

### PR DESCRIPTION
**Pull request by Lan-ce-lot**
Signed-off-by: Lancelot [1984737645@qq.com](mailto:1984737645@qq.com)

### Describe what this PR does / why we need it

Fix the duplicate of the result list.

### Does this pull request fix one issue?

Fixes #190.

### Describe how you did it

By using a hash table to Record the filesystem that appears, if the filesystem already exists, it doesn't append.

### Describe how to verify it

image

Before

image

after de-duplicated the resulting list.

image

### Special notes for reviews

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -244,6 +244,7 @@ func main() {
 	// validate arguments
 	if len(flag.Args()) > 0 {
 		var mounts []Mount
+		vis := make(map[string]bool)
```
Comment (muesli) [inline main.go:247]: It doesn't make much difference in this particular case, but generally speaking, you can use a `map[string]struct{}`, which avoids the extra allocation for a bool.

File: main.go [hunk 2]
```diff
@@ -252,8 +253,16 @@ func main() {
 				fmt.Println(err)
 				os.Exit(1)
 			}
-
-			mounts = append(mounts, fm...)
+			// de-duplicate
+			var tmp []Mount
+			for _, v := range fm {
+				if _, ok := vis[v.Device]; !ok {
+					tmp = append(tmp, v)
```
Comment (muesli) [inline main.go:260]: Instead of keeping a temporary slice, we can just directly append to `mounts` here.

**Review by muesli — CHANGES_REQUESTED** [review]
Just small cleanups, looks good otherwise!

File: main.go (hunk 2 above)
Comment (Lan-ce-lot) [reply main.go]: Thank you for your suggestion, I have modified it

**Comment by Lan-ce-lot** [comment]
> Just small cleanups, looks good otherwise!

PTAL

**Comment by gj67668838** [comment]
sounds good.

**Comment by C0rn3j** [comment]
@muesli Anything else this needs?

**Review by muesli — APPROVED** [review]
