### PR TITLE
[Linux] fix escaped type & filesystem

### LINKED ISSUE #65: Escaped character in type & filesystem field
When type or filesystem filed in `/proc/self/mountinfo` contains escaped character, it will be displayed in escaped form.

For example, when I make a mount point with a `\` character at the end of its type or filesystem.
What I supposed to see:
```
│ MOUNTED ON                        │ SIZE │ USED │ AVAIL │ USE% │ TYPE                   │ FILESYSTEM        │
├───────────────────────────────────┼──────┼──────┼───────┼──────┼────────────────────────┼───────────────────┤
│ /tmp/mnt                          │   0B │   0B │    0B │      │ fuse.hello\            │ hello\            │
```
What I actually see:
```
│ MOUNTED ON                        │ SIZE │ USED │ AVAIL │ USE% │ TYPE                   │ FILESYSTEM        │
├───────────────────────────────────┼──────┼──────┼───────┼──────┼────────────────────────┼───────────────────┤
│ /tmp/mnt                          │   0B │   0B │    0B │      │ fuse.hello\134         │ hello\134         │
```
What `df` says:
```
Filesystem                              Type                   1K-blocks     Used Available Use% Mounted on
hello\                                  fuse.hello\                    0        0         0    - /tmp/mnt
```
What `/proc/self/mountinfo` says:
```
862 54 0:68 / /tmp/mnt rw,nosuid,nodev,relatime shared:470 - fuse.hello\134 hello\134 rw,user_id=1000,group_id=1000
```
`\134` clearly is the escaped format of `\`.

This issue is also reported on WSL by @SuperSandro2000 https://github.com/muesli/duf/issues/56#issuecomment-704842831

### PR DESCRIPTION
**Pull request by RangerCD**
Fix #65

### CODE REVIEW

File: mounts_linux.go [hunk 1]
```diff
@@ -43,8 +43,8 @@ func mounts() ([]Mount, []string, error) {
 		mountOpts := fields[5]
 
 		fields = strings.Fields(parts[1])
-		fstype := fields[0]
-		device := fields[1]
+		fstype := unescapeFstab(fields[0])
```
Comment (muesli) [inline mounts_linux.go:46]: I wonder if we need that for other unix variants as well. My guess is we do.

Comment (RangerCD) [reply mounts_linux.go:46]: Current implmentation of other unix systems are based on `unix.Getfsstat` insteadof directly reading from `/proc/self/mountinfo`. I think those characters should be unescaped since it's passed through API. Unfortunately, I can't verify my assumption, cause I don't have any device with other unix system. :disappointed:

Comment (muesli) [reply mounts_linux.go:46]: Good point!
